apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api
  labels:
    app: order-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      labels:
        app: order-api
    spec:
      containers:
      - name: order-api
        image: order-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8002
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "orderapi.settings"
        - name: MONGODB_HOST
          value: "mongodb-service"
        - name: MONGODB_PORT
          value: "27017"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: order-api-service
  labels:
    app: order-api
spec:
  selector:
    app: order-api
  ports:
  - port: 8002
    targetPort: 8002
    protocol: TCP
  type: LoadBalancer
